blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/zerovoids/zerovoids-utils/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/zerovoids/zerovoids-utils#readme
    about: Read the documentation for usage examples
